{% set version = "7.1.0" %}
{% set minor_version = ".".join(version.split(".")[:2]) %}

package:
  name: vtk_blesbok
  version: {{ version }}

source:
  git_url: https://gitlab.kitware.com/dfroger/vtk.git
  git_rev: PainterCommunicator

build:
  number: 0
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]
  skip: True  # [osx or (linux and py34)]

requirements:
  build:
    - toolchain
    - cmake
    - ninja
    - python
    # VTK Third Party dependencies
    - zlib 1.2.*
    - freetype 2.6.*
    - hdf5 1.8.17|1.8.17.*  # [unix]
    - libxml2
    - libpng >=1.6.21,<1.7
    - jpeg 9*
    - libtiff 4.0.*
    - jsoncpp  # [unix]
    - expat
  run:
    - python
    - future  # used in the generated python wrappers
    # VTK Third Party dependencies
    - zlib 1.2.*
    - freetype 2.6.*
    - hdf5 1.8.17|1.8.17.*  # [unix]
    - libxml2
    - libpng >=1.6.21,<1.7
    - jpeg 9*
    - libtiff 4.0.*
    - jsoncpp  # [unix]
    - expat

test:
  imports:
    - vtk
    - vtk.vtkChartsCore
    - vtk.vtkCommonCore
    - vtk.vtkFiltersCore
    - vtk.vtkFiltersGeneric
    - vtk.vtkGeovisCore
    - vtk.vtkFiltersHybrid
    - vtk.vtkIOCore
    - vtk.vtkImagingCore
    - vtk.vtkInfovisCore
    - vtk.vtkRenderingCore
    - vtk.vtkViewsCore
    - vtk.vtkRenderingVolume
    - vtk.vtkInteractionWidgets

about:
  home: http://www.vtk.org/
  license: BSD 3-Clause
  summary: >
    The Visualization Toolkit (VTK) is an open-source, freely available software
    system for 3D computer graphics, modeling, image processing, volume 
    rendering, scientific visualization, and information visualization.

extra:
  recipe-maintainers:
    - Korijn
    - ivoflipse
    - Maxyme
    - ccordoba12
    - grlee77
    - msarahan
    - patricksnape
    - dfroger
